### ISSUE TITLE
How to run on inside-out data?

### ISSUE THREAD

**Issue by ghy0324** [ventusff/neurecon#1]
Hi! Thank you for the excellent project!
I am going to run VolSDF on inside-out data such as indoor scenes.
Could you give me some advice on how to setup the parameters?

**Comment by ventusff** [comment]
Hi!
After quick thinking, there are two options(maybe not fully correct):
- Turning the scene inside out.
  - Revert the initialization (make ||x||<r means outside, make ||x||>r means inside). This could be done by directly multiplying the weights with `-1` after regular init.
  - Ensure that all cameras are inside the scene initially. This could be done by properly normalizing the cameras and initializing a sphere with large enough radius. (large enough `model: surface: radius_init`).
  - For VolSDF, make sure `self.use_bg_sphere` is False (since the cameras are already "inside" the whole scene, rays are already always-intersected-at-the-end), and `use_nerfplusplus` is False (since the camera is always "inside" and there are no infinely-far backgrounds).
- Or, making the mapping function workable under the inside-out configuration.
  - As for VolSDF, it should be directly workable.
  - As for UNISURF, some ray-intersection mechanisms should be altered by some flags.
  - As for NeuS, some signs should be reversed when mapping sdf to alpha.
 
Some of the setup needs hard-coded modifications right now if you want to proceed. I will do some experiments and release changes so that everything is done simply adding some configs like `model: inside_out: True` in a few days, if that's needed :)
