### ISSUE TITLE
Positional encoding in `RadianceNet`

### ISSUE THREAD

**Issue by shrubb** [ventusff/neurecon#2]
Hi, and thanks a lot for the implementation!

https://github.com/ventusff/neurecon/blob/972e810ec252cfd16f630b1de6d2802d1b8de59a/configs/volsdf_nerfpp_blended.yaml#L41-L42

I was wondering why we are not using positional encoding and instead are feeding raw 3D coordinates and view directions here? Especially because IDR [is not doing so](https://github.com/lioryariv/idr/blob/44959e7aac267775e63552d8aac6c2e9f2918cca/code/confs/dtu_fixed_cameras.conf#L49) and [the defaults are 6 and 4](https://github.com/ventusff/neurecon/blob/972e810ec252cfd16f630b1de6d2802d1b8de59a/models/base.py#L318-L319)... 🤔

I tried changing these from -1 to 6 and/or 4, and training collapses or at least goes much slower... To me, this seems extremely weird!

**Comment by ventusff** [comment]
Hi @shrubb,
Yes, I agree that the `embed_multire_view` should be `4` in every case. 
Sorry that this is not carefully configured before, because in my practice embedding for radiance network seems to not have noticeable influence.

However, the raw 3D coordinates may still be directly feeded, as in [IDR](https://github.com/lioryariv/idr/blob/44959e7aac267775e63552d8aac6c2e9f2918cca/code/model/implicit_differentiable_renderer.py#L140), in a way of respecting official choice of implementation. But of course feeding embeded input may lead to better results.

As for the training speed, in my test:

### volsdf.yaml

- only setting `embed_multires_view=4`:

```shell
  ....
  (radiance_net): RadianceNet(
    (embed_fn): Identity()
    (embed_fn_view): Embedder()
    (layers): ModuleList(
      (0): DenseLayer(
        in_features=289, out_features=256, bias=True
        (activation): ReLU(inplace=True)
      )
  ...
  0%|           | 97/100000 [00:25<6:06:50,  4.54it/s, loss_img=0.135, loss_total=0.137, lr=0.000499]
```

- setting `6&4`:
```shell
  (radiance_net): RadianceNet(
    (embed_fn): Embedder()
    (embed_fn_view): Embedder()
    (layers): ModuleList(
      (0): DenseLayer(
        in_features=325, out_features=256, bias=True
        (activation): ReLU(inplace=True)
      )
...
0%|             | 107/100000 [00:28<6:07:23,  4.53it/s, loss_img=0.16, loss_total=0.164, lr=0.000499]
```

### volsdf_nerfpp_blended.yaml

You may notice that the training iterations arise from `100k` to `200k`, which is the major reason of training time increase.

- original `-1&-1` setting:
```shell
0%|           | 131/200000 [00:34<14:43:28,  3.77it/s, loss_img=0.182, loss_total=0.185, lr=0.0005]
```

- only setting `embed_multires_view=4`:

```shell
0%|           | 209/200000 [00:52<13:54:47,  3.99it/s, loss_img=0.215, loss_total=0.22, lr=0.0005]
```

- setting `6&4`:

```shell
0%|            | 121/200000 [00:32<14:50:09,  3.74it/s, loss_img=0.162, loss_total=0.163, lr=0.0005]
```

**Comment by ventusff** [comment]
As for whether training collapses or not, I'm running training tests on BlendedMVS, to be continued...

**Comment by shrubb** [comment]
Thanks for sharing your experience and especially for linking the IDR code! 🙏 Now it makes more sense.

By "slower" I actually meant convergence speed and training stability. Like, when I apply positional encodings to radiance net's inputs (pink graph), losses/metrics/parameters go crazy, while with your default config training is smooth and stable (blue graph). I'll continue to investigate this.
![изображение](https://user-images.githubusercontent.com/9570420/135619396-7cefb3a6-4717-451f-871b-8d5365fcfcb9.png)
![изображение](https://user-images.githubusercontent.com/9570420/135619501-953af70b-c86e-415c-9222-35061057a357.png)
![изображение](https://user-images.githubusercontent.com/9570420/135619583-3f5fe4c7-dfaf-4ac7-9dec-98fecc438d18.png)

**Comment by ventusff** [comment]
Hi @shrubb ,
After running some training tests, I think a possible explanation can be made, which is also something I found out earlier:

At early training stage, the dominating representing branch **needs to be** the `geometry_feature`, for the network to quickly find initial clues about a roughly correct shape to render correct images. 

If the embeded 3D coordinates are feeded to radiance network instead of raw 3D coordinates (`dim=39` instead of `dim=3`), then the representing capability is branched with ambiguity, the network may assign more representing capability to the radiance itself instead of learning a rough shape, thus leading to very slow shape convergence (and may not even converge at all)

That is to say, the dominating representing branch needs to be the first one among the following three at early stages:
```
x -> embedder -> SDF -> geometry_feature -> radiance
x -> (embedder) -> radiance
v -> (embedder) -> radiance
```

Embedding location and view direction input of radiance network introduce larger gradients and "prempt" more gradients flows to the radiance net, "sharing" relatively less gradients to the surface network, as shown below:

<img width="434" alt="微信截图_20211001210127" src="https://user-images.githubusercontent.com/25529198/135624061-554cb6ab-90f2-43e1-ae33-a22ab7acb1da.png">
<img width="415" alt="微信截图_20211001210139" src="https://user-images.githubusercontent.com/25529198/135624066-5ebd3bd0-ea51-466a-b88e-1f7837c8f576.png">

 

Pratical comparison of normals validation when training: (You can see that no meaningful shapes are learned in the latter two cases)
- `embed_x=-1 & embed_v=-1` @ 0k,1k,2k
![00000000_0](https://user-images.githubusercontent.com/25529198/135622155-160223a7-346f-45b9-9ef7-079449f26f09.png)
![00001000_0](https://user-images.githubusercontent.com/25529198/135622213-b45d2189-222f-4651-b328-857bcbfb5382.png)
![00002000_0](https://user-images.githubusercontent.com/25529198/135622225-d4393ecc-a2e1-400d-83ea-626fb399a09d.png)

- `embed_x=-1 & embed_v=4` @ 0k,1k,2k
![00000000_0](https://user-images.githubusercontent.com/25529198/135623347-37c37a2a-8fae-4e39-be0b-641b6dce7181.png)
![00001000_0](https://user-images.githubusercontent.com/25529198/135622411-be380242-dfb3-4033-b6c9-4c6fe2bcef29.png)
![00002000_0](https://user-images.githubusercontent.com/25529198/135622511-4479b7f5-efc7-482f-9efc-82254bf2826e.png)


- `embed_x=6 & embed_v=4` @ 0k,1k,2k
![00000000_0](https://user-images.githubusercontent.com/25529198/135622650-b3f95856-b7cf-4e2d-a4d5-ea721cc2dbb8.png)
![00001000_0](https://user-images.githubusercontent.com/25529198/135622665-86b6265e-1ab1-4e06-a53f-719189e6b0d7.png)
![00002000_0](https://user-images.githubusercontent.com/25529198/135622692-7c06b5ef-eee0-4dad-bd0c-6bdb4b86b9ba.png)

**Comment by ventusff** [comment]
But still, in `VolSDF`, embedding view_direction even leads to no convergence. This is still weird, since it's OK with `NeuS`.

The `VolSDF` paper mentioned nothing about whether the input of radiance network is embedded or not. I'm looking forward to their official implementation for code comparison.

**Comment by shrubb** [comment]
Makes perfect sense, thank you for the insight and the experiments! 🎉

**Comment by ventusff** [comment]
Glad to know it helps 😄
